//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.431
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_IDE.D {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DIcons() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D_IDE.D.DIcons", typeof(DIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap cmd {
            get {
                object obj = ResourceManager.GetObject("cmd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] d_xshd {
            get {
                object obj = ResourceManager.GetObject("d_xshd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon dfile {
            get {
                object obj = ResourceManager.GetObject("dfile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dfile16 {
            get {
                object obj = ResourceManager.GetObject("dfile16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dfile32 {
            get {
                object obj = ResourceManager.GetObject("dfile32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dll48 {
            get {
                object obj = ResourceManager.GetObject("dll48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon dproj {
            get {
                object obj = ResourceManager.GetObject("dproj", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dproj16 {
            get {
                object obj = ResourceManager.GetObject("dproj16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dproj32 {
            get {
                object obj = ResourceManager.GetObject("dproj32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dproj48 {
            get {
                object obj = ResourceManager.GetObject("dproj48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Generic_Application {
            get {
                object obj = ResourceManager.GetObject("Generic_Application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Class {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Class", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Delegate {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Delegate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Enum {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Enum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Field {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Field", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Interface {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Interface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_InternalClass {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_InternalClass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_InternalDelegate {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_InternalDelegate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_InternalEnum {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_InternalEnum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_InternalField {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_InternalField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_InternalInterface {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_InternalInterface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_InternalMethod {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_InternalMethod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_InternalProperty {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_InternalProperty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_InternalStruct {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_InternalStruct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Keyword {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Keyword", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Literal {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Literal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Local {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Local", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Method {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Method", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_NameSpace {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_NameSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Parameter {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Parameter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PrivateClass {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PrivateClass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PrivateDelegate {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PrivateDelegate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PrivateEnum {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PrivateEnum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PrivateEvent {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PrivateEvent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PrivateField {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PrivateField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PrivateInterface {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PrivateInterface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PrivateMethod {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PrivateMethod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PrivateProperty {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PrivateProperty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_PrivateStruct {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_PrivateStruct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Property {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_ProtectedClass {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_ProtectedClass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_ProtectedDelegate {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_ProtectedDelegate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_ProtectedEnum {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_ProtectedEnum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_ProtectedField {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_ProtectedField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_ProtectedInterface {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_ProtectedInterface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_ProtectedMethod {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_ProtectedMethod", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_ProtectedProperty {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_ProtectedProperty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_ProtectedStruct {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_ProtectedStruct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icons_16x16_Struct {
            get {
                object obj = ResourceManager.GetObject("Icons_16x16_Struct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
