//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D_IDE.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D_IDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap build {
            get {
                object obj = ResourceManager.GetObject("build", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap build_dbg {
            get {
                object obj = ResourceManager.GetObject("build_dbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap build_prj {
            get {
                object obj = ResourceManager.GetObject("build_prj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version = &quot;1.0&quot;?&gt;
        ///&lt;!-- D mode VS.NET style --&gt;
        ///&lt;!-- Alexander Bothe edit --&gt;
        ///&lt;SyntaxDefinition name = &quot;D&quot; extensions = &quot;.d&quot;&gt;
        ///
        ///  &lt;Environment&gt;
        ///    &lt;Default      color = &quot;SystemColors.WindowText&quot; bgcolor=&quot;SystemColors.Window&quot;/&gt;
        ///    &lt;Selection    color = &quot;SystemColors.HighlightText&quot; bgcolor = &quot;SystemColors.Highlight&quot;/&gt;
        ///    &lt;!--		&lt;Selection    bgcolor = &quot;LightBlue&quot;/&gt; --&gt;
        ///    &lt;VRuler       color = &quot;SystemColors.ControlLight&quot;/&gt;
        ///    &lt;InvalidLines color = &quot;Red&quot;/&gt;
        ///    &lt;CaretMarker  color = &quot;Yellow&quot;/ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap d_16 {
            get {
                object obj = ResourceManager.GetObject("d_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon d_file {
            get {
                object obj = ResourceManager.GetObject("d_file", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon d_ide {
            get {
                object obj = ResourceManager.GetObject("d_ide", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap d_ide_256 {
            get {
                object obj = ResourceManager.GetObject("d_ide_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon dprj {
            get {
                object obj = ResourceManager.GetObject("dprj", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dprj_16 {
            get {
                object obj = ResourceManager.GetObject("dprj_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap new_prj {
            get {
                object obj = ResourceManager.GetObject("new_prj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap prj_prop {
            get {
                object obj = ResourceManager.GetObject("prj_prop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version = &quot;1.0&quot;?&gt;
        ///&lt;!-- D mode VS.NET style --&gt;
        ///&lt;!-- Alexander Bothe edit --&gt;
        ///&lt;SyntaxDefinition name = &quot;RC&quot; extensions = &quot;.rc&quot;&gt;
        ///
        ///  &lt;Environment&gt;
        ///    &lt;Default      color = &quot;SystemColors.WindowText&quot;    bgcolor = &quot;SystemColors.Window&quot;/&gt;
        ///    &lt;Selection    color = &quot;SystemColors.HighlightText&quot; bgcolor = &quot;SystemColors.Highlight&quot;/&gt;
        ///    &lt;!--		&lt;Selection    bgcolor = &quot;LightBlue&quot;/&gt; --&gt;
        ///    &lt;VRuler       color = &quot;SystemColors.ControlLight&quot;/&gt;
        ///    &lt;InvalidLines color = &quot;Red&quot;/&gt;
        ///    &lt;CaretMarker  color = &quot;Y [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string RC {
            get {
                return ResourceManager.GetString("RC", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap save_all {
            get {
                object obj = ResourceManager.GetObject("save_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap step_in {
            get {
                object obj = ResourceManager.GetObject("step_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap step_out {
            get {
                object obj = ResourceManager.GetObject("step_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap step_over {
            get {
                object obj = ResourceManager.GetObject("step_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stop_build {
            get {
                object obj = ResourceManager.GetObject("stop_build", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
